[package]
name = "darkruby-tictactoe"
version = "0.2.0"
authors = ["Art Deineka"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.6"
rayon = "1.0"
